{% set name = "depinfo" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6b25e75ef32e317bbb5f750b8a62bbf90aa193ac8328646edac30856063f8bb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - importlib_metadata  # [py<38]

test:
  imports:
    - depinfo

about:
  home: https://github.com/Midnighter/dependency-info
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: List any package's direct dependencies and their versions.
  description: >
    A utility Python package intended for other library packages.
    Provides a function that when called with your package name,
    will print platform and dependency information.
  doc_url: https://github.com/Midnighter/dependency-info
  dev_url: https://github.com/Midnighter/dependency-info

extra:
  recipe-maintainers:
    - cdiener
    - Midnighter
