{% set name = "depinfo" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0971be11519a823b126c875e17ad3ad8adaa6a86737395b9dbcef3ca0e77b0c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer-518
  run:
    - python >={{ python_min }}
    - pip
    - importlib_metadata

test:
  requires:
    - python {{ python_min }}
  imports:
    - depinfo

about:
  home: https://github.com/Midnighter/dependency-info
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: List any package's direct dependencies and their versions.
  description: >
    A utility Python package intended for other library packages. Provides a function that when called with your package name, will print platform and dependency information.
  doc_url: https://github.com/Midnighter/dependency-info
  dev_url: https://github.com/Midnighter/dependency-info

extra:
  recipe-maintainers:
    - cdiener
    - Midnighter
