{% set name = "depinfo" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4d052c685f6ac0a5e9972efd317dcd0daa8d65bad69218ea1fda4d607202ca3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - pipdeptree >=0.13.2

test:
  imports:
    - depinfo

about:
  home: https://github.com/Midnighter/dependency-info
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: List a package's direct dependencies and their versions.
  description: |
    A utility Python package intended for other library packages.
    Provides a function that when called with your package name,
    will print platform and dependency information.
  doc_url: https://github.com/Midnighter/dependency-info
  dev_url: https://github.com/Midnighter/dependency-info

extra:
  recipe-maintainers:
    - cdiener
    - Midnighter
