travis:
  secure:
    BINSTAR_TOKEN: a1Wb48jbpYjAnz9NmC80et05Q9yioEqiIK3ZW4uVHAqarPUvzrsWDb7NBddHqmB10usdkmF4msnRhWiaN2uw+jWgyLSvIv9NyH75D41v3mSdR7O9N6EtLn0HXqzvBUvdirijXdr/B8/AkMSdQgISGERL016sZzCaq2mkquDMGocaGIt+O1/TRB6Mp3itYBigwT9nU19zErK7eWqxdKvoH4Qu38AT05E22T2sWBSSAlHTbIUm0VmUDbOhemTgByMqeCcypTK9oEEJojpVU8vnaAPITLb6DSMToguOdSCBSBRye0BgxrTPreqUcyuWII+HwYrIc38WFumtgBpbohGh+GHdtvO99ZvCelK1tuCfmSPr9y4dWtNDd3I1HQfp6KcnlDD2B49OqwBKI+ycSu4iDfD295Vh56F5B5wWkUUfrlBeAZncMY1r+95dZZh1NhHAf7RL3KW8uIhjXB3GTwKUCH8H6X2s4sywxDsRPP3A+JXwSA2cLTvc4sIDcyT3IzGNkqVRnryJW2a304cgt8MsLWmDXZr61jO76ptevJBYQ05kRztC40nzaHrGUKvsArqTLUg6yIjbAtsQJfN1IpPePfvjYQedoS/f/nbttT1d+XVWYFfup9R2Bm0QVSwLFVs9towo/cUE8EtTgQw4F+ci/BiZlZdgpVzKZSd3vH0pxaY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
