travis:
  secure:
    BINSTAR_TOKEN: tJwHfG/YIOHxBc0VhfVTE3Fb/ZFyY2gR/0wYmFk/baX2hCmtOwvwYi8JenHojRcOCQPStocBT81naIUWwWKeTSKg/hEmLJd1bZHMdGITtXQzeyfndEK8UwiK/jUyImBYbkJwtuBfCr0d/Qcor5vSN++cj8KXTZZmIzoLuis8Yo2eQ+BVUSLGsexObRIaqk0xFl00O34KiIsoG8W0E3TnzkVyGHu0O/r4H56Zpoqc4V8iSw3nbe2zK1Klv+/Dhvn09hxPOzS4RRariwM+X3as8mCzHL+ODI8zrCjyEghwZsd1VyHJZhyLEC7DdYxAkev+uJMNNLmfG7eTRKUUZHz8yeGDj1BKGSOFYZT8bKd5UNFwuc0gogmkTrxRD2Kn6d+swOW74WYUs/U1Di9m1l3BEyRzzt2DsEyEyzip9jKEw97EYTtZA9EraTC0h9KBKRH7DPp/x/GWzFlgFpTSFh2tLBk0ViZnBMqjky6igsDfUbyqN+HRWVyk4DRYyw/gvINk/jm2oyjy1EJ2iIT2L9bDAUhBq8rV93+LiwL2TcpPpb/tGgcSpW9N4XLfadxtdX6DyR9/RZX9jpr6mBnSm3YVv6cQ88pjrouUQ5uOXH9s1XG6JrtT3guxbtjAnCM9Qnx6skn+zDInJM3lxuzJI4PpbPZSGXr3BEZE5ChuDWoqUWo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
